In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
import seaborn as sns
from collections import defaultdict
%matplotlib inline

df = pd.read_csv('./febrile_seizures.csv')
df.head()

,Gender,Social Status,Age,Education level,Working in health,Where are you living,child had convulsions,Temperature cause convulsions,Spasm is a type of epilepsy,Is it dangerous up to 5 years,...,Child with cramps should be placed on his left or right side,necessary to observe the apparent child characteristics,Child should be taken to the doctor immediately,Put anything inside child mouth prevent child from biting his teeth with force,Child must be resuscitated by introducing air through mouth,Secretions should be withdrawn,Heart must be refreshed,Dealing with a child when has a cramp,having thermometer at home,Know how to use thermometer
0,male,Single,20 - 25,college,Health,Eastern,No,Yes,No,Yes,...,Dont Know,Yes,No,No,No,Yes,No,Yes,Yes,Yes
1,Female,Single,20 - 25,college,nonH,Eastern,No,Yes,Dont Know,Yes,...,Dont Know,Yes,Dont Know,Dont Know,Dont Know,Dont Know,Dont Know,Dont Know,No,Yes
2,male,Married,26 - 40,college,nonH,Eastern,No,Yes,No,Yes,...,Dont Know,Yes,No,Dont Know,No,No,No,Dont Know,Yes,Yes
3,Female,Married,40 - 60,college,nonH,Eastern,No,Yes,No,Yes,...,Dont Know,Yes,No,Yes,Yes,Yes,Dont Know,No,Yes,Yes
4,Female,Married,40 - 60,college,Health,Eastern,No,Yes,Yes,Yes,...,Dont Know,Yes,No,Yes,Dont Know,Dont Know,Dont Know,Dont Know,Yes,Yes

In [3]:
#Show the numbers of users depend on working in health

health = df['Working in health'].value_counts().reset_index()
health.head()

    index  Working in health
0    nonH                750
1  Health                 77

In [11]:
# number of users by province

province = df['Where are you living '].value_counts().reset_index()
province.head()

     index  Where are you living
0  Eastern                    523
1   middle                    194
2     West                     63
3    south                     27
4    north                     16

In [15]:
#Change index to appropriate name = method

province.rename(columns={'index': 'method', 'Where are you living': 'count'}, inplace=True)
province.head()

    method  Where are you living
0  Eastern                    523
1   middle                    194
2     West                     63
3    south                     27
4    north                     16